export const tripData = [
  {
    id: 1,
    tripName: "Viaje a la playa",
    amount: 1250.75,
    status: "Pendiente",
    date: "2025-02-15",
    destination: "Cancún, Quintana Roo",
    duration: 5,
    passengers: 3,
    transportation: "Avión",
    requestDate: "2025-03-01",
  },
  {
    id: 2,
    tripName: "Viaje a la montaña",
    amount: 2400.5,
    status: "Aprobado",
    date: "2025-01-22",
    destination: "Valle de Bravo",
    duration: 3,
    passengers: 4,
    transportation: "Automóvil",
    requestDate: "2025-02-05",
  },
  {
    id: 3,
    tripName: "Viaje a la ciudad",
    amount: 1750.0,
    status: "Rechazado",
    date: "2024-12-10",
    destination: "Ciudad de México",
    duration: 2,
    passengers: 2,
    transportation: "Autobús",
    requestDate: "2024-12-28",
  },
  {
    id: 4,
    tripName: "Viaje al campo",
    amount: 3200.25,
    status: "Pendiente",
    date: "2025-03-05",
    destination: "Rancho Los Álamos",
    duration: 4,
    passengers: 6,
    transportation: "Camioneta",
    requestDate: "2025-03-20",
  },
  {
    id: 5,
    tripName: "Viaje a la selva",
    amount: 4500.0,
    status: "Aprobado",
    date: "2024-11-18",
    destination: "Chiapas",
    duration: 7,
    passengers: 2,
    transportation: "Avión",
    requestDate: "2024-12-05",
  },
  {
    id: 6,
    tripName: "Viaje al pueblo mágico",
    amount: 1800.5,
    status: "En revisión",
    date: "2025-02-28",
    destination: "San Miguel de Allende",
    duration: 3,
    passengers: 4,
    transportation: "Automóvil",
    requestDate: "2025-03-15",
  },
  {
    id: 7,
    tripName: "Viaje al desierto",
    amount: 3850.75,
    status: "Pendiente",
    date: "2025-01-10",
    destination: "San Luis Potosí",
    duration: 5,
    passengers: 3,
    transportation: "Camioneta",
    requestDate: "2025-02-01",
  },
  {
    id: 8,
    tripName: "Tour gastronómico",
    amount: 2750.0,
    status: "Rechazado",
    date: "2024-10-25",
    destination: "Oaxaca",
    duration: 4,
    passengers: 2,
    transportation: "Avión",
    requestDate: "2024-11-10",
  },
  {
    id: 9,
    tripName: "Viaje de negocios",
    amount: 5200.25,
    status: "Aprobado",
    date: "2025-03-12",
    destination: "Monterrey",
    duration: 6,
    passengers: 1,
    transportation: "Avión",
    requestDate: "2025-03-25",
  },
  {
    id: 10,
    tripName: "Viaje cultural",
    amount: 2900.5,
    status: "En revisión",
    date: "2025-02-05",
    destination: "Querétaro",
    duration: 3,
    passengers: 5,
    transportation: "Autobús",
    requestDate: "2025-02-20",
  },
];

export const spendOptions = [
  { value: "daily_allowance", label: "Viáticos diarios" },
  { value: "toll_fees", label: "Casetas de peaje" },
  { value: "accommodation", label: "Hospedaje y alojamiento" },
  { value: "fuel", label: "Combustible y recarga" },
  { value: "meals", label: "Alimentación en viaje" },
  { value: "local_transport", label: "Transporte local (taxis, Uber)" },
  { value: "tickets", label: "Boletos de avión/tren/autobús" },
  { value: "parking", label: "Tarifas de estacionamiento" },
  { value: "vehicle_rental", label: "Renta de vehículos" },
  { value: "business_meetings", label: "Comidas de negocios/reuniones" },
  { value: "services", label: "Servicios de internet/teléfono" },
  { value: "unexpected", label: "Gastos imprevistos" },
  { value: "other_travel", label: "Otros gastos de viaje" },
];

export const taxIndicatorOptions = [
  { value: "taxable", label: "Gravado" },
  { value: "exempt", label: "Exento" },
  { value: "not_applicable", label: "No aplica" },
];
