name: Check PR Target Branch

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main

jobs:
  check-target:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR to main is from develop
        if: github.base_ref == 'main' && github.head_ref != 'develop' && !startsWith(github.head_ref, 'release/') && !startsWith(github.head_ref, 'hotfix/')
        run: |
          echo "⚠️ ERROR: PRs to main should only come from develop, release/* or hotfix/* branches."
          echo "Please retarget your PR to the develop branch instead."
          exit 1
