name: Check PR Target Branch
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  check-target-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR target
        run: |
          # Get PR details using github.event context
          TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
          echo "Pull Request from $SOURCE_BRANCH to $TARGET_BRANCH"

          # Check if this is a PR to main
          if [[ "$TARGET_BRANCH" == "main" ]]; then
            # Check if source branch is allowed to target main (only develop)
            if [[ "$SOURCE_BRANCH" == "develop" ]]; then
              echo "✅ Valid PR: $SOURCE_BRANCH can target main"
            else
              echo "::error::❌ BRANCH TARGET ERROR: Invalid PR from '$SOURCE_BRANCH' to 'main'"
              echo "::error::According to our GitFlow process, PRs to 'main' can ONLY come from:"
              echo "::error::- develop (for planned releases)"
              echo "::error::Please close this PR and create a new one targeting 'develop' instead."
              exit 1
            fi
          else
            echo "✅ This PR is targeting '$TARGET_BRANCH', no restrictions apply"
          fi
