name: Check PR Target Branch

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main # This specifies the action only runs on PRs targeting main

jobs:
  check-target:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR to main is from allowed branches
        run: |
          if [[ "${{ github.base_ref }}" == "main" && 
                "${{ github.head_ref }}" != "develop" && 
                "${{ github.head_ref }}" != release/* && 
                "${{ github.head_ref }}" != hotfix/* ]]; then
            echo "::error::❌ BRANCH TARGET ERROR: Invalid PR from '${{ github.head_ref }}' to 'main'"
            echo "::error::This PR is coming from '${{ github.head_ref }}', which is not allowed to target 'main' directly."
            echo ""
            echo "According to our GitFlow process:"
            echo "✅ ALLOWED: PRs to 'main' can ONLY come from:"
            echo "   - develop (for planned releases)"
            echo "   - release/* (for version preparations)"
            echo "   - hotfix/* (for urgent production fixes)"
            echo ""
            echo "❓ SOLUTION: Please close this PR and create a new one targeting 'develop' instead."
            echo "   If this is a feature or bugfix, it must be integrated into 'develop' first."
            exit 1
          fi
